# Generated by Django 5.0.1 on 2024-02-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField(max_length=100)),
                ('messg', models.TextField(max_length=500)),
            ],
        ),
    ]
