# Generated by Django 5.0.1 on 2024-02-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_site', '0003_rename_name_product_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(max_length=300),
        ),
    ]
