# Generated by Django 5.0.1 on 2024-02-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_site', '0006_cartitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
    ]
