# Generated by Django 5.0.1 on 2024-02-10 14:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_site', '0007_rename_cartitems_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
