# Generated by Django 5.0.1 on 2024-02-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_site', '0008_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
